# Options for ...
Brower_Options: 
  Browser_Name: ""  # Options: firefox, chrome, edge (leave blank for window's assigned default browser)
Productivity_Antidote:
  Bop_It_Enabled: False
  Mouse_Wiggler: False
Productivity_Punishments: 
  Rick_Roll: True
  Tab_Zapper: True
  Tab_Shuffler: False
  Fake_Tab_Shuffler: False
  Pop_Up_Generator: False 
  Noise_Maker: False
  Constellation_Mode: False
  Brainrot_Mode: False
  
